package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// Default go microsvc skel HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new go microsvc skel HTTP client.
func NewHTTPClient(formats strfmt.Registry) *GoMicrosvcSkel {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http"})
	return New(transport, formats)
}

// New creates a new go microsvc skel client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *GoMicrosvcSkel {
	cli := new(GoMicrosvcSkel)
	cli.Transport = transport

	return cli
}

// GoMicrosvcSkel is a client for go microsvc skel
type GoMicrosvcSkel struct {
	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *GoMicrosvcSkel) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

}
